# Data Cleaning Notebook - Beginner Friendly Version

This notebook cleans the salary dataset step by step.

The goal is simple:

1. Load the raw CSV file.
2. Check the data.
3. Clean missing values and duplicates.
4. Make coded values easier to read.
5. Remove invalid salary rows.
6. Save a cleaned CSV file for the training notebook.

The original raw CSV file will not be changed.

## 1. Import libraries and load the dataset

We only need `pandas` here.

`pandas` helps us read CSV files and work with tables.

In [1]:
import pandas as pd

# This is the path of the original raw dataset.
raw_path = "../data/raw/ds_salaries.csv"

# Read the CSV file and store it inside a DataFrame called df.
df = pd.read_csv(raw_path)

# Show the first 5 rows.
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

## 2. Check the dataset

Before cleaning, we should understand the data.

We will check:

- Number of rows and columns
- Column names
- Data types
- Basic statistics

In [2]:
# Number of rows and columns
df.shape

(607, 12)

In [3]:
# Column names
df.columns

Index(['Unnamed: 0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size'],
      dtype='str')

In [4]:
# Information about each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    str
 3   employment_type     607 non-null    str
 4   job_title           607 non-null    str
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    str
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    str
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    str
 11  company_size        607 non-null    str
dtypes: int64(5), str(7)
memory usage: 57.0 KB

In [5]:
# Summary statistics for numeric columns
df.describe()

       Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

## 3. Clean column names

Some column names can have uppercase letters or spaces.

We will make all column names:

- Lowercase
- Without extra spaces
- With `_` instead of spaces

In [6]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

# Check the new column names.
df.columns

Index(['unnamed:_0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size'],
      dtype='str')

## 4. Remove missing values and duplicate rows

Missing values means empty cells.

Duplicate rows means the same row is repeated more than one time.

In [7]:
# Check how many missing values exist in each column.
df.isnull().sum()

unnamed:_0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [8]:
# Save the number of rows before cleaning.
rows_before = len(df)

# Remove rows that have missing values.
df = df.dropna()

# Remove duplicate rows.
df = df.drop_duplicates()

# Save the number of rows after cleaning.
rows_after = len(df)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Rows removed:", rows_before - rows_after)

Rows before: 607
Rows after: 607
Rows removed: 0

## 5. Clean text columns

Some text values may have extra spaces.

Example:

`"Data Scientist "` should become `"Data Scientist"`.

In [9]:
text_columns = [
    "experience_level",
    "employment_type",
    "job_title",
    "employee_residence",
    "company_location",
    "company_size"
]

for column in text_columns:
    df[column] = df[column].astype(str)
    df[column] = df[column].str.strip()

df.head()

,unnamed:_0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

## 6. Replace short codes with readable words

The dataset uses short codes.

For example:

- `EN` means `Entry-level`
- `MI` means `Mid-level`
- `SE` means `Senior-level`
- `EX` means `Executive-level`

We will replace these codes with clear names.

In [10]:
# Replace experience level codes.
df["experience_level"] = df["experience_level"].replace({
    "EN": "Entry-level",
    "MI": "Mid-level",
    "SE": "Senior-level",
    "EX": "Executive-level"
})

# Replace employment type codes.
df["employment_type"] = df["employment_type"].replace({
    "FT": "Full-time",
    "PT": "Part-time",
    "CT": "Contract",
    "FL": "Freelance"
})

# Replace company size codes.
df["company_size"] = df["company_size"].replace({
    "S": "Small",
    "M": "Medium",
    "L": "Large"
})

df.head()

,unnamed:_0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,Mid-level,Full-time,Data Scientist,70000,EUR,79833,DE,0,DE,Large
1,1,2020,Senior-level,Full-time,Machine Learning Scientist,260000,USD,260000,JP,0,JP,Small
2,2,2020,Senior-level,Full-time,Big Data Engineer,85000,GBP,109024,GB,50,GB,Medium
3,3,2020,Mid-level,Full-time,Product Data Analyst,20000,USD,20000,HN,0,HN,Small
4,4,2020,Senior-level,Full-time,Machine Learning Engineer,150000,USD,150000,US,50,US,Large

In [11]:
# Check if the replacement worked.
print(df["experience_level"].value_counts())
print()
print(df["employment_type"].value_counts())
print()
print(df["company_size"].value_counts())

experience_level
Senior-level       280
Mid-level          213
Entry-level         88
Executive-level     26
Name: count, dtype: int64

employment_type
Full-time    588
Part-time     10
Contract       5
Freelance      4
Name: count, dtype: int64

company_size
Medium    326
Large     198
Small      83
Name: count, dtype: int64

## 7. Make sure numeric columns are numbers

Some columns must be numbers, especially salary columns.

We will convert them to numeric values.

In [12]:
numeric_columns = [
    "work_year",
    "salary",
    "salary_in_usd",
    "remote_ratio"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

# If conversion failed, pandas will create missing values.
df[numeric_columns].isnull().sum()

work_year        0
salary           0
salary_in_usd    0
remote_ratio     0
dtype: int64

## 8. Remove invalid salary rows

Salary values should not be empty, zero, or negative.

We will keep only valid salary rows.

In [13]:
rows_before = len(df)

# Remove rows where numeric values became missing.
df = df.dropna(subset=numeric_columns)

# Keep only positive salary values.
df = df[df["salary"] > 0]
df = df[df["salary_in_usd"] > 0]

rows_after = len(df)

print("Rows removed:", rows_before - rows_after)
print("Rows remaining:", rows_after)

Rows removed: 0
Rows remaining: 607

In [14]:
# Convert these columns to whole numbers.
df["work_year"] = df["work_year"].astype(int)
df["remote_ratio"] = df["remote_ratio"].astype(int)

df[numeric_columns].describe()

         work_year        salary  salary_in_usd  remote_ratio
count   607.000000  6.070000e+02     607.000000     607.00000
mean   2021.405272  3.240001e+05  112297.869852      70.92257
std       0.692133  1.544357e+06   70957.259411      40.70913
min    2020.000000  4.000000e+03    2859.000000       0.00000
25%    2021.000000  7.000000e+04   62726.000000      50.00000
50%    2022.000000  1.150000e+05  101570.000000     100.00000
75%    2022.000000  1.650000e+05  150000.000000     100.00000
max    2022.000000  3.040000e+07  600000.000000     100.00000

## 9. Remove very high salary outliers

An outlier is a value that is much higher or lower than most values.

Very high salary values can confuse the model.

To keep this simple, we will remove salaries above the 99th percentile.

This means we keep most rows and remove only the highest extreme salaries.

In [15]:
# Check salary distribution first.
df["salary_in_usd"].describe()

count       607.000000
mean     112297.869852
std       70957.259411
min        2859.000000
25%       62726.000000
50%      101570.000000
75%      150000.000000
max      600000.000000
Name: salary_in_usd, dtype: float64

In [16]:
rows_before = len(df)

# Find the 99th percentile salary.
salary_limit = df["salary_in_usd"].quantile(0.99)

# Keep only salaries less than or equal to the limit.
df = df[df["salary_in_usd"] <= salary_limit]

rows_after = len(df)

print("Salary limit:", salary_limit)
print("Rows removed:", rows_before - rows_after)
print("Rows remaining:", rows_after)

Salary limit: 403499.99999999854
Rows removed: 7
Rows remaining: 600

## 10. Group rare job titles

Some job titles appear only a few times.

This can make the model harder to train.

We will replace job titles that appear fewer than 5 times with `Other`.

In [17]:
# Count how many times each job title appears.
job_title_counts = df["job_title"].value_counts()

job_title_counts

job_title
Data Scientist                              142
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           15
Data Science Manager                         12
Data Architect                               11
Machine Learning Scientist                    8
Big Data Engineer                             8
Data Science Consultant                       7
Director of Data Science                      7
AI Scientist                                  7
Data Analytics Manager                        7
Lead Data Engineer                            6
BI Data Analyst                               6
ML Engineer                                   6
Computer Vision Engineer                      6
Principal Data Scientist                      6
Business Data Analyst                         5
Data Engineering Manager                      5
Head of Data                                  5
Applied Data Scientist                        5
Data Analytics Engineer                       4
Head of Data Science                          4
Analytics Engineer                            4
Lead Data Scientist                           3
Lead Data Analyst                             3
Machine Learning Infrastructure Engineer      3
Computer Vision Software Engineer             3
Data Science Engineer                         3
Machine Learning Developer                    3
Applied Machine Learning Scientist            3
Product Data Analyst                          2
Cloud Data Engineer                           2
Director of Data Engineering                  2
Principal Data Engineer                       2
Principal Data Analyst                        2
ETL Developer                                 2
Machine Learning Manager                      1
3D Computer Vision Researcher                 1
Marketing Data Analyst                        1
Data Specialist                               1
Finance Data Analyst                          1
Big Data Architect                            1
Staff Data Scientist                          1
Head of Machine Learning                      1
NLP Engineer                                  1
Lead Machine Learning Engineer                1
Financial Data Analyst                        1
Name: count, dtype: int64

In [18]:
# Job titles that appear fewer than 5 times are rare.
rare_job_titles = job_title_counts[job_title_counts < 5].index

# Replace rare job titles with Other.
df.loc[df["job_title"].isin(rare_job_titles), "job_title"] = "Other"

print("Number of rare job titles:", len(rare_job_titles))
print("Number of job titles after grouping:", df["job_title"].nunique())

Number of rare job titles: 27
Number of job titles after grouping: 23

## 11. Create a work setting column

The `remote_ratio` column uses numbers:

- `0` means On-site
- `50` means Hybrid
- `100` means Remote

We will create a new readable column called `work_setting`.

In [19]:
def get_work_setting(remote_ratio):
    if remote_ratio == 0:
        return "On-site"
    elif remote_ratio == 50:
        return "Hybrid"
    elif remote_ratio == 100:
        return "Remote"
    else:
        return "Unknown"


df["work_setting"] = df["remote_ratio"].apply(get_work_setting)

df[["remote_ratio", "work_setting"]].drop_duplicates()

   remote_ratio work_setting
0             0      On-site
2            50       Hybrid
5           100       Remote

In [20]:
# Remove rows with unknown remote values, if any exist.
df = df[df["work_setting"] != "Unknown"]

df["work_setting"].value_counts()

work_setting
Remote     376
On-site    126
Hybrid      98
Name: count, dtype: int64

## 12. Choose final columns

Now we select only the columns that we need for training and analysis.

In [21]:
final_columns = [
    "work_year",
    "experience_level",
    "employment_type",
    "job_title",
    "employee_residence",
    "remote_ratio",
    "work_setting",
    "company_location",
    "company_size",
    "salary_in_usd"
]

clean_df = df[final_columns]

clean_df.head()

,work_year,experience_level,employment_type,job_title,employee_residence,remote_ratio,work_setting,company_location,company_size,salary_in_usd
0,2020,Mid-level,Full-time,Data Scientist,DE,0,On-site,DE,Large,79833
1,2020,Senior-level,Full-time,Machine Learning Scientist,JP,0,On-site,JP,Small,260000
2,2020,Senior-level,Full-time,Big Data Engineer,GB,50,Hybrid,GB,Medium,109024
3,2020,Mid-level,Full-time,Other,HN,0,On-site,HN,Small,20000
4,2020,Senior-level,Full-time,Machine Learning Engineer,US,50,Hybrid,US,Large,150000

## 13. Final check

Before saving, we check:

- Final shape
- Missing values
- Salary statistics

In [22]:
print("Final shape:", clean_df.shape)

print()
print("Missing values:")
print(clean_df.isnull().sum())

print()
print("Salary statistics:")
print(clean_df["salary_in_usd"].describe())

Final shape: (600, 10)

Missing values:
work_year             0
experience_level      0
employment_type       0
job_title             0
employee_residence    0
remote_ratio          0
work_setting          0
company_location      0
company_size          0
salary_in_usd         0
dtype: int64

Salary statistics:
count       600.000000
mean     108348.011667
std       60763.132982
min        2859.000000
25%       62650.500000
50%      100000.000000
75%      150000.000000
max      380000.000000
Name: salary_in_usd, dtype: float64

## 14. Save the cleaned dataset

We save the cleaned file inside:

`../data/processed/cleaned_salaries.csv`

This file will be used in the model training notebook.

In [23]:
# Create the output folder if it does not exist.
import os

output_folder = "../data/processed"
os.makedirs(output_folder, exist_ok=True)

# Save the cleaned dataset.
output_path = "../data/processed/cleaned_salaries.csv"
clean_df.to_csv(output_path, index=False)

print("Cleaned dataset saved here:")
print(output_path)

Cleaned dataset saved here:
../data/processed/cleaned_salaries.csv