# load dataset

In [43]:
import pandas as pd
import numpy as np

raw_path ="..\\data\\raw\\ds_salaries.csv"

df = pd.read_csv(raw_path)

df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

# check basic dataset info

In [44]:
df.shape

(607, 12)

In [45]:
df.info

<bound method DataFrame.info of      Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT
1             1       2020               SE              FT
2             2       2020               SE              FT
3             3       2020               MI              FT
4             4       2020               SE              FT
..          ...        ...              ...             ...
602         602       2022               SE              FT
603         603       2022               SE              FT
604         604       2022               SE              FT
605         605       2022               SE              FT
606         606       2022               MI              FT

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833
1    Machine Learning Scientist  260000             USD         260000
2             Big Data Engineer   85000             GBP         109024
3          Product Data Analyst   20000             USD          20000
4     Machine Learning Engineer  150000             USD         150000
..                          ...     ...             ...            ...
602               Data Engineer  154000             USD         154000
603               Data Engineer  126000             USD         126000
604                Data Analyst  129000             USD         129000
605                Data Analyst  150000             USD         150000
606                AI Scientist  200000             USD         200000

    employee_residence  remote_ratio company_location company_size
0                   DE             0               DE            L
1                   JP             0               JP            S
2                   GB            50               GB            M
3                   HN             0               HN            S
4                   US            50               US            L
..                 ...           ...              ...          ...
602                 US           100               US            M
603                 US           100               US            M
604                 US             0               US            M
605                 US           100               US            M
606                 IN           100               US            L

[607 rows x 12 columns]>

In [46]:
df.describe(include='all')

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
count,607.000000,607.000000,607,607,607,6.070000e+02,607,607.000000,607,607.00000,607,607
unique,NaN,NaN,4,4,50,NaN,17,NaN,57,NaN,50,3
top,NaN,NaN,SE,FT,Data Scientist,NaN,USD,NaN,US,NaN,US,M
freq,NaN,NaN,280,588,143,NaN,398,NaN,332,NaN,355,326
mean,303.000000,2021.405272,NaN,NaN,NaN,3.240001e+05,NaN,112297.869852,NaN,70.92257,NaN,NaN
std,175.370085,0.692133,NaN,NaN,NaN,1.544357e+06,NaN,70957.259411,NaN,40.70913,NaN,NaN
min,0.000000,2020.000000,NaN,NaN,NaN,4.000000e+03,NaN,2859.000000,NaN,0.00000,NaN,NaN
25%,151.500000,2021.000000,NaN,NaN,NaN,7.000000e+04,NaN,62726.000000,NaN,50.00000,NaN,NaN
50%,303.000000,2022.000000,NaN,NaN,NaN,1.150000e+05,NaN,101570.000000,NaN,100.00000,NaN,NaN
75%,454.500000,2022.000000,NaN,NaN,NaN,1.650000e+05,NaN,150000.000000,NaN,100.00000,NaN,NaN
max,606.000000,2022.000000,NaN,NaN,NaN,3.040000e+07,NaN,600000.000000,NaN,100.00000,NaN,NaN

# Standardize column names

In [47]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.columns

Index(['unnamed:_0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size'],
      dtype='str')

# check for missing values

In [48]:
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values

unnamed:_0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [49]:
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)
missing_percent

unnamed:_0            0.0
work_year             0.0
experience_level      0.0
employment_type       0.0
job_title             0.0
salary                0.0
salary_currency       0.0
salary_in_usd         0.0
employee_residence    0.0
remote_ratio          0.0
company_location      0.0
company_size          0.0
dtype: float64

In [50]:
df = df.dropna()
df.shape

(607, 12)

# check duplicates

In [51]:
df.duplicated().sum()
df = df.drop_duplicates()

df.shape

(607, 12)

# clean text columns

In [52]:
categorical_columns = [
    "experience_level",
    "employment_type",
    "job_title",
    "employee_residence",
    "company_location",
    "company_size",
]

for col in categorical_columns:
    df[col] = df[col].astype(str).str.strip()

df.head()

,unnamed:_0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

# check for unique values

In [53]:
for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].value_counts())

experience_level
experience_level
SE    280
MI    213
EN     88
EX     26
Name: count, dtype: int64

employment_type
employment_type
FT    588
PT     10
CT      5
FL      4
Name: count, dtype: int64

job_title
job_title
Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Machine Learning Scientist                    8
Big Data Engineer                             8
Data Science Consultant                       7
Director of Data Science                      7
AI Scientist                                  7
Principal Data Scientist                      7
Data Analytics Manager                        7
Lead Data Engineer                            6
BI Data Analyst                               6
ML Engineer                                   6
Computer Vision Engineer                      6
Business Data Analyst                         5
Data Engineering Manager                      5
Head of Data                                  5
Applied Data Scientist                        5
Data Analytics Engineer                       4
Applied Machine Learning Scientist            4
Head of Data Science                          4
Analytics Engineer                            4
Lead Data Scientist                           3
Lead Data Analyst                             3
Machine Learning Infrastructure Engineer      3
Computer Vision Software Engineer             3
Data Science Engineer                         3
Principal Data Engineer                       3
Machine Learning Developer                    3
Product Data Analyst                          2
Cloud Data Engineer                           2
Financial Data Analyst                        2
Director of Data Engineering                  2
Principal Data Analyst                        2
ETL Developer                                 2
Machine Learning Manager                      1
3D Computer Vision Researcher                 1
Marketing Data Analyst                        1
Data Specialist                               1
Finance Data Analyst                          1
Big Data Architect                            1
Staff Data Scientist                          1
Head of Machine Learning                      1
NLP Engineer                                  1
Lead Machine Learning Engineer                1
Data Analytics Lead                           1
Name: count, dtype: int64

employee_residence
employee_residence
US    332
GB     44
IN     30
CA     29
DE     25
FR     18
ES     15
GR     13
JP      7
PK      6
PT      6
BR      6
NL      5
PL      4
RU      4
IT      4
AE      3
AT      3
VN      3
TR      3
AU      3
HU      2
MX      2
NG      2
DK      2
SG      2
BE      2
RO      2
SI      2
HN      1
NZ      1
CN      1
PH      1
HR      1
BG      1
IQ      1
UA      1
MT      1
CL      1
IR      1
CO      1
MD      1
KE      1
HK      1
RS      1
PR      1
LU      1
JE      1
CZ      1
AR      1
DZ      1
TN      1
MY      1
EE      1
BO      1
IE      1
CH      1
Name: count, dtype: int64

company_location
company_location
US    355
GB     47
CA     30
DE     28
IN     24
FR     15
ES     14
GR     11
JP      6
NL      4
AT      4
PT      4
PL      4
PK      3
AE      3
MX      3
DK      3
LU      3
BR      3
TR      3
AU      3
CN      2
NG      2
IT      2
BE      2
RU      2
SI      2
CH      2
CZ      2
HN      1
HU      1
NZ      1
HR      1
SG      1
RO      1
IQ      1
UA      1
IL      1
MT      1
CL      1
IR      1
CO      1
MD      1
KE      1
VN      1
AS      1
DZ      1
EE      1
MY      1
IE      1
Name: count, dtype: int64

company_size
company_size
M    326
L    198
S     83
Name: count, dtype: int64

# rename coded values

In [54]:
experience_map = {
    "EN": "Entry-level",
    "MI": "Mid-level",
    "SE": "Senior-level",
    "EX": "Executive-level",
}

employment_map = {
    "FT": "Full-time",
    "PT": "Part-time",
    "CT": "Contract",
    "FL": "Freelance",
}

company_size_map = {"S": "Small", "M": "Medium", "L": "Large"}

df["experience_level"] = df["experience_level"].replace(experience_map)
df["employment_type"] = df["employment_type"].replace(employment_map)
df["company_size"] = df["company_size"].replace(company_size_map)

df.head()

,unnamed:_0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,Mid-level,Full-time,Data Scientist,70000,EUR,79833,DE,0,DE,Large
1,1,2020,Senior-level,Full-time,Machine Learning Scientist,260000,USD,260000,JP,0,JP,Small
2,2,2020,Senior-level,Full-time,Big Data Engineer,85000,GBP,109024,GB,50,GB,Medium
3,3,2020,Mid-level,Full-time,Product Data Analyst,20000,USD,20000,HN,0,HN,Small
4,4,2020,Senior-level,Full-time,Machine Learning Engineer,150000,USD,150000,US,50,US,Large

# clean numeric columns

In [55]:
numeric_columns = ["work_year", "salary", "salary_in_usd", "remote_ratio"]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna(subset=numeric_columns)

df[numeric_columns].info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   work_year      607 non-null    int64
 1   salary         607 non-null    int64
 2   salary_in_usd  607 non-null    int64
 3   remote_ratio   607 non-null    int64
dtypes: int64(4)
memory usage: 19.1 KB

# remove invalid salary rows

In [56]:
df = df[df["salary_in_usd"] > 0]
df = df[df["salary"] > 0]

df.shape

(607, 12)

# check remote ratio values

In [57]:
df["remote_ratio"].value_counts().sort_index()

remote_ratio
0      127
50      99
100    381
Name: count, dtype: int64

In [58]:
remote_map = {0: "On-site", 50: "Hybrid", 100: "Remote"}

df["work_setting"] = df["remote_ratio"].map(remote_map)

df[["remote_ratio", "work_setting"]].head()

   remote_ratio work_setting
0             0      On-site
1             0      On-site
2            50       Hybrid
3             0      On-site
4            50       Hybrid

# decide ml columns

In [59]:
model_df = df[
    [
        "work_year",
        "experience_level",
        "employment_type",
        "job_title",
        "employee_residence",
        "remote_ratio",
        "work_setting",
        "company_location",
        "company_size",
        "salary_in_usd",
    ]
].copy()

model_df.head()

,work_year,experience_level,employment_type,job_title,employee_residence,remote_ratio,work_setting,company_location,company_size,salary_in_usd
0,2020,Mid-level,Full-time,Data Scientist,DE,0,On-site,DE,Large,79833
1,2020,Senior-level,Full-time,Machine Learning Scientist,JP,0,On-site,JP,Small,260000
2,2020,Senior-level,Full-time,Big Data Engineer,GB,50,Hybrid,GB,Medium,109024
3,2020,Mid-level,Full-time,Product Data Analyst,HN,0,On-site,HN,Small,20000
4,2020,Senior-level,Full-time,Machine Learning Engineer,US,50,Hybrid,US,Large,150000

In [60]:
model_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           607 non-null    int64
 1   experience_level    607 non-null    str
 2   employment_type     607 non-null    str
 3   job_title           607 non-null    str
 4   employee_residence  607 non-null    str
 5   remote_ratio        607 non-null    int64
 6   work_setting        607 non-null    str
 7   company_location    607 non-null    str
 8   company_size        607 non-null    str
 9   salary_in_usd       607 non-null    int64
dtypes: int64(3), str(7)
memory usage: 47.6 KB

In [61]:
model_df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
employee_residence    0
remote_ratio          0
work_setting          0
company_location      0
company_size          0
salary_in_usd         0
dtype: int64

In [62]:
model_df.duplicated().sum()

np.int64(42)

In [63]:
model_df = model_df.drop_duplicates()
model_df.shape

(565, 10)

# save new processed data

In [64]:
processed_path = "../data/processed/cleaned_salaries.csv"

model_df.to_csv(processed_path, index=False)

print(f"Cleaned dataset saved to: {processed_path}")

Cleaned dataset saved to: ../data/processed/cleaned_salaries.csv